version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn cheferv1.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/var/www/html
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: django_nginx
    ports:
      - "8080:80"  # container Nginx exposed to host at port 8080
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./home/static:/var/www/html/home/static
    depends_on:
      - web

